import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, backgroundColor: "#f5f5f5" },
  noListsText: {fontSize: 16, fontWeight: "bold", color:"green", marginTop: 50},
  header: { fontSize: 24, fontWeight: "bold", marginBottom: 10 },
  listRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 5 },
  listButton: { flex: 1, padding: 10, backgroundColor: "#ddd", marginVertical: 5, borderRadius: 5 },
  listText: { fontSize: 18 },
  deleteText: { fontSize: 20, color: "red", paddingHorizontal: 10 },
  input: { borderWidth: 1, padding: 10, marginVertical: 10, borderRadius: 5 },
  floatingButtonRight: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#28a745",
    borderRadius: 50,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  floatingButtonLeft: {
    position: "absolute",
    bottom: 20,
    left: 20,
    backgroundColor: "#0d6efd",
    borderRadius: 50,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  floatingButtonLeftUp: {
    position: "absolute",
    bottom: 90,
    left: 20,
    backgroundColor: "#0d6efd",
    borderRadius: 50,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  plusIcon: { color: "white", fontSize: 30, fontWeight: "bold" },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  downArrowIcon: {
    fontSize:40,
    position: "absolute",
    right:50,
    top: 300,
    transform:[{rotate: '-20deg'}]
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    gap: 10,
    borderRadius: 10,
    width: "80%",
  },
});
